backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'
media_folder: static/img
public_folder: /img
collections:
  - name: blog
    label: Blog
    folder: src/pages/blog
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - label: Template Key
        name: templateKey
        widget: hidden
        default: blog-post
      - label: Titulo
        name: title
        widget: string
      - label: Data de publicação
        name: date
        widget: datetime
      - label: Descrição
        name: description
        widget: text
      - label: Featured Post
        name: featuredpost
        widget: hidden
      - label: Imagem principal
        name: featuredimage
        widget: image
      - label: Texto
        name: body
        widget: markdown
      - label: Tags
        name: tags
        widget: list
  - name: pages
    label: Paginas
    files:
      - file: src/pages/index.md
        label: Pagina inicial
        name: index
        fields:
          - label: Template Key
            name: templateKey
            widget: hidden
            default: index-page
          - label: O que é terapia
            name: whatIsTherapy
            widget: object
            fields:
              - label: Titulo
                name: title
                widget: string
              - label: Corpo
                name: body
                widget: text
              - label: Corpo italico
                name: body2
                widget: text

          - label: Tipos de terapia
            name: typesOfTherapy
            widget: object
            fields:
              - label: Titulo 1
                name: title1
                widget: string
              - label: Corpo 1
                name: body1
                widget: text
              - label: Imagem 1
                name: image1
                widget: image
              - label: Descrição da Imagem 1
                name: image1alt
                type: string
              - label: Titulo 2
                name: title2
                widget: string
              - label: Corpo 2
                name: body2
                widget: text
              - label: Imagem 2
                name: image2
                widget: image
              - label: Descrição da Imagem 2
                name: image2alt
                type: string
              - label: Titulo 3
                name: title3
                widget: string
              - label: Corpo 3
                name: body3
                widget: text
              - label: Imagem 3
                name: image3
                widget: image
              - label: Descrição da Imagem 3
                name: image3alt
                type: string

          - label: Para quem
            name: forWho
            widget: object
            fields:
              - label: Titulo
                name: title
                widget: string
              - label: Texto do botão
                name: buttonLabel
                widget: string
              - label: Tipos
                name: types
                widget: object
                fields:
                  - label: Individual
                    name: individual
                    widget: object
                    fields:
                      - label: Titulo
                        name: title
                        widget: string
                      - label: Corpo
                        name: body
                        type: text
                      - label: URL
                        name: url
                        widget: string
                      - label: Descrição da imagem
                        name: imgAlt
                        widget: string
                      - label: Imagem
                        name: image
                        widget: image
                  - label: Casal
                    name: couple
                    widget: object
                    fields:
                      - label: Titulo
                        name: title
                        widget: string
                      - label: Corpo
                        name: body
                        type: text
                      - label: URL
                        name: url
                        widget: string
                      - label: Descrição da imagem
                        name: imgAlt
                        widget: string
                      - label: Imagem
                        name: image
                        widget: image

          - label: Quem Faz
            name: aboutBarbara
            widget: object
            fields:
              - label: Titulo
                name: title
                widget: string
              - label: Corpo
                name: body
                widget: text
              - label: URL
                name: url
                type: string
              - label: Texto do botão
                name: buttonLabel
                type: string
              - label: Descrição da imagem
                name: imgAlt
                type: string
              - label: Imagem
                name: image
                widget: image

          - label: Contato
            name: contact
            widget: object
            fields:
              - label: Titulo
                name: title
                widget: string
              - label: Corpo
                name: body
                widget: text
              - label: Texto do botão
                name: buttonLabel
                type: string
              - label: Whatsapp
                name: whatsappNumber
                type: string

      - file: src/pages/terapia-individual/index.md
        label: Terapia individual
        name: terapia-individual
        fields:
          - label: Template Key
            name: templateKey
            widget: hidden
            default: terapia-individual
          - label: Titulo
            name: title
            widget: string
          - label: Primeiro text
            name: firstText
            widget: text
          - label: Imagem
            name: image
            widget: image
          - label: Texto em italico
            name: italicText
            widget: text
          - label: Segundo titulo
            name: secondTitle
            widget: string
          - label: Segundo texto
            name: secondText
            widget: text
          - label: Whatsapp
            name: whatsappNumber
            type: string

      - file: src/pages/terapia-de-casal/index.md
        label: Terapia de casal
        name: terapia-de-casal
        fields:
          - label: Template Key
            name: templateKey
            widget: hidden
            default: terapia-de-casal
          - label: Titulo
            name: title
            widget: string
          - label: Primeiro text
            name: firstText
            widget: text
          - label: Imagem
            name: image
            widget: image
          - label: Texto em italico
            name: italicText
            widget: text
          - label: Segundo titulo
            name: secondTitle
            widget: string
          - label: Segundo texto
            name: secondText
            widget: text
          - label: Whatsapp
            name: whatsappNumber
            type: string

      - file: src/pages/sobre.md
        label: Sobre
        name: sobre
        fields:
          - label: Template Key
            name: templateKey
            widget: hidden
            default: about-page
          - label: Titulo
            name: title
            widget: hidden
          - label: Texto parte 1
            name: noQueAcredito1
            widget: text
          - label: Texto parte 2
            name: noQueAcredito2
            widget: text
          - label: Texto parte 3
            name: noQueAcredito3
            widget: text
          - label: Imagem
            name: noQueAcreditoImg
            widget: image
          - label: Experiencia
            name: experiencia
            widget: text
            
  - name: about-roll
    label: Fotos sobre
    folder: src/pages/sobre
    create: false
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - label: Template Key
        name: templateKey
        widget: hidden
        default: about-post
      - label: Title
        name: title
        widget: string
      - label: Ordem
        name: order
        widget: number
        value_type: "int"
        min: 1
        max: 10
      - label: Texto
        name: description
        widget: text
      - label: Imagem
        name: featuredimage
        widget: image

